version: 2.0.1
name: MBedwarsHotbarManager
author: MetallicGoat
main: me.metallicgoat.hotbarmanageraddon.HotbarManagerPlugin
description: Adds a hotbar manager to MBedwars
api-version: 1.13
depend: [MBedwars]